<a href="https://colab.research.google.com/github/ANDRESHZ/ANDRESHZIIC3633-2020/blob/master/%5CPracticos%5CpyRecLab_SlopeOne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://youtu.be/A2euuevpYis" target="_parent"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/YouTube_full-color_icon_%282017%29.svg/71px-YouTube_full-color_icon_%282017%29.svg.png" alt="Open In Colab"/></a>


# **Práctico Sistemas Recomendadores: pyreclab - Slope One**

En este práctico seguiremos utilizando [pyreclab](https://github.com/gasevi/pyreclab), con el cual estamos aprendiendo distintas técnicas de recomendación. Seguiremos usando la misma base de datos de los prácticos anteriores, para que puedan comparar los métodos y sus implementaciones. Este práctico está acompañado de un [video comentando la actividad](https://youtu.be/A2euuevpYis).

En esta oportunidad exploraremos el recomendador de Pendiente Uno o **Slope One** [1].

**Adaptado y preparado por:** Francisca Cattan 📩 fpcattan@uc.cl

Referencias 📖
------
[1] *Lemire, D., & Maclachlan, A. (2005, April). Slope One Predictors for Online Rating-Based Collaborative Filtering. In SDM (Vol. 5, pp. 1-5).*


**Nombre**:  completa tu nombre aquí :D

## Actividad 1 👓

Antes de empezar con el práctico, responde la siguiente pregunta con lo visto en clases.

**Pregunta:** Explique cómo funciona Slope One (como modelo teórico, no piense en la implementación). En particular explique:

- Repasemos: ¿Por qué este recomendador es un algoritmo de Filtrado Colaborativo?
- Este Filtrado Colaborativo, ¿está basado en el usuario o en los items? ¿Por qué?
- ¿Qué datos recibe Slope One y qué hace con ellos? (qué tipo de columnas y qué calculo)
- ¿Qué pasaría si se agrega un nuevo rating a la base de datos?
- Opcional: ¿Cómo crees que le iría al recomendador con un usuario que acaba de entrar al sistema y ha asignado muy pocos ratings?

💡 *Hint: La bibliografía todo lo puede.*

**Respuesta:**

- debido a que usa la información proporcionada por distintos usuarios para predecir los valores a asociar a cada posible caso.
- de forma directa en la interacción con de Usuarios-items, así pues los dos debido a que depende de que datos estén presentes y que usuario hayan sido los calificadores.
-calcula desviaciones y promedios, para dar predicción a las columnas a predecir, y con base a la matriz de interacción ofrece una predicción (para recomendar basta con organizar los ratings).
-no podría emplearse ninguna desviación ni acción, se debe contar con alguna interacción para poder predecir.
-Bastante mal, debido a que no tendrá valores con los cuales aplicar predicción, su valoración estaría alejada de su realidad debido a  la baja muestra de información del usuario



# **Configuración Inicial**

## Paso 1:
Descargue directamente a Colab los archivos del dataset ejecutando las siguientes 3 celdas:


In [1]:
!curl -L -o "u1.base" "https://drive.google.com/uc?export=download&id=1bGweNw7NbOHoJz11v6ld7ymLR8MLvBsA"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   388    0   388    0     0    340      0 --:--:--  0:00:01 --:--:--   340
100 1546k  100 1546k    0     0  1090k      0  0:00:01  0:00:01 --:--:-- 1090k


In [2]:
!curl -L -o "u1.test" "https://drive.google.com/uc?export=download&id=1f_HwJWC_1HFzgAjKAWKwkuxgjkhkXrVg"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   388    0   388    0     0    577      0 --:--:-- --:--:-- --:--:--   577
100  385k  100  385k    0     0   436k      0 --:--:-- --:--:-- --:--:--  436k


In [3]:
!curl -L -o "u.item" "https://drive.google.com/uc?export=download&id=10YLhxkO2-M_flQtyo9OYV4nT9IvSESuz"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   388    0   388    0     0    725      0 --:--:-- --:--:-- --:--:--   723
100  230k  100  230k    0     0   285k      0 --:--:-- --:--:-- --:--:--  285k


Los archivos **u1.base** y **u1.test** tienen tuplas {usuario, item, rating, timestamp}, que es la información de preferencias de usuarios sobre películas en una muestra del dataset [movielens](https://grouplens.org/datasets/movielens/).

## Paso 2:

Instalamos pyreclab utilizando pip.

In [4]:
!pip install pyreclab --upgrade

     |████████████████████████████████| 235kB 6.1MB/s 


## Paso 3:

Hacemos los imports necesarios para este práctico.

In [5]:
import pyreclab
import numpy as np
import pandas as pd

# **El dataset**

💡 *En prácticos anteriores, vimos como analizar este dataset. Puedes revisarlos en caso de dudas.*

## Paso 4:

Ya que queremos crear una lista de recomendación de items para un usuario en especifico, necesitamos obtener información adicional de cada película tal como título, fecha de lanzamiento, género, etc. Cargaremos el archivo de items descargado "u.item" para poder mapear cada identificador de ítem al conjunto de datos que lo describe.

In [6]:
# Definimos el orden de las columnas
info_cols = [ 'movieid', 'title', 'release_date', 'video_release_date', 'IMDb_URL', \
              'unknown', 'Action', 'Adventure', 'Animation', 'Children', 'Comedy', \
              'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', \
              'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western' ]

# Asignamos a una variable la estructura de datos de los items
info_file = pd.read_csv('u.item', sep='|', index_col = 0, names = info_cols, header=None, encoding='latin-1')

# **Slope One**

## Paso 5:

Seguiremos un camino muy similar a los ejercicios de User KNN e Item KNN. Crearemos una instancia del algoritmo de recomendación y luego pasaremos a la fase de entrenamiento.

In [8]:
# Declaramos la instancia SlopeOne
mySlopeOne = pyreclab.SlopeOne(dataset='u1.base', dlmchar=b'\t', header=False, usercol=0, itemcol=1, ratingcol=2)

In [20]:
# Y enntrenamos
mySlopeOne.train()

## Actividad 2 👓

**Pregunta:** Explique qué hace el método `train()` en este caso, dado el modelo teórico. ¿Calcula información?, ¿no hace nada?, ¿ordena los datos? 

**Respuesta:**
Supondria que calcula las desviaciones con usuarios en común y dispone los datos para posterior uso.

Observando lso pasos subsecuentes ordena y agrupa información de los items y usuarios. 

## Paso 6:

Llego la hora de predecir el rating.

In [11]:
# Esta es la predicción de rating que el usuario ID:457 otorgaría al ítem ID:37
# De esta forma podemos comparar el resultado con los prácticos anteriores
mySlopeOne.predict("457", "37")

3.5898244380950928

In [13]:
# También podemos guardar la predicción en una variable
prediction = mySlopeOne.predict("457", "37")

In [15]:
# Podemos comprobar las peliculas rankeadas por el usuario ID:457
# Que ciertamente ha participado activamente (¡156 items!)
train_file = pd.read_csv('u1.base', sep='\t', names = ['userid', 'itemid', 'rating', 'timestamp'], header=None)
train_file[train_file['userid'] == 457]

userid  itemid  rating  timestamp
37269     457       1       4  882393244
37270     457       7       4  882393278
37271     457       9       5  882393485
37272     457      11       4  882397020
37273     457      13       3  882393883
...       ...     ...     ...        ...
37420     457    1047       2  882395964
37421     457    1119       4  882398308
37422     457    1168       5  882548761
37423     457    1210       4  882549905
37424     457    1221       4  882549438

[156 rows x 4 columns]

In [16]:
# Y también cuáles usuarios han rankeado la pelicula ID:37
train_file[train_file['itemid'] == 37]

userid  itemid  rating  timestamp
1302       13      37       1  882397011
14851     201      37       2  884114635
19670     268      37       3  876514002
29489     363      37       2  891498510
31084     385      37       4  880013483
32996     405      37       1  885548384
62777     773      37       3  888540352

## Actividad 3 👓

Haremos un pequeño experimento para entender mejor como funciona Slope One. Gracias al ejercicio anterior, sabemos que el usuario 457 ya ha asignado el mejor rating (5 ⭐) a las dos peliculas ID:9 e ID:1168. Comparemos.

**Pregunta:** ¿Cómo se explican estos resultados?  

**Respuesta:** debido aq ue el modelo aplica sobre esta los valores de otro usuarios que han rankeado otros items en comun con ese usuario.

In [17]:
prediction_id9 = mySlopeOne.predict("457", "9")
prediction_id1168 = mySlopeOne.predict("457", "1168")

print('Prediction for ID:9 :', prediction_id9)
print('Prediction for ID:1168 :', prediction_id1168)

Prediction for ID:9 : 4.385906219482422
Prediction for ID:1168 : 4.206681251525879


## Paso 7:

Generaremos ahora una lista ordenada de las top-N recomendaciones, dado un usuario.



In [18]:
# Mediante el método recommend() genereremos una lista top-5 recomendaciones para el usuario ID:457
reclist_slopeone = mySlopeOne.recommend("457", 5)

# Y visualizaremos el resultado
print('Lista de items según ID:', reclist_slopeone)

Lista de items según ID: ['1592', '1589', '1656', '1431', '1653']


In [19]:
# Lo convertimos a numpy array
recmovies_slopeone = np.array(reclist_slopeone).astype(int)

# Utilizamos la estructura de datos de los items para encontrar los títulos recomendados
print('Lista de items por nombre:')
info_file.loc[recmovies_slopeone]['title']

Lista de items por nombre:


movieid
1592                               Magic Hour, The (1998)
1589                                   Schizopolis (1996)
1656                                   Little City (1998)
1431                                  Legal Deceit (1997)
1653    Entertaining Angels: The Dorothy Day Story (1996)
Name: title, dtype: object

## Actividad 4 👩🏻‍💻

Genera una nueva recomendacion, modificando los hiperparametros de usuario y topN a tu elección.

**Pregunta:** ¿Ves una diferencia en la recomendación entre el nuevo usuario y el usuario ID:457?

**Respuesta:**

si multiples pues depende de los datos que el a rankeado y las desviaciones

In [27]:
# Escribe el nuevo codigo aqui
u="200"
reclist_slopeone2 = mySlopeOne.recommend(u, 5)
print('Lista de items según ID:', reclist_slopeone2)
reclist_slopeone2 = mySlopeOne.recommend(u, 10)
print('Lista de items según ID:', reclist_slopeone2)

Lista de items según ID: ['1656', '1064', '1651', '1650', '1645']
Lista de items según ID: ['1656', '1064', '1651', '1650', '1645', '1642', '1636', '1585', '1599', '1512']


In [26]:
# Escribe el nuevo codigo aqui
u="123"
reclist_slopeone2 = mySlopeOne.recommend(u, 10)
print('Lista de items según ID:', reclist_slopeone2)

Lista de items según ID: ['1599', '814', '1512', '1656', '1500', '1201', '1523', '1122', '1450', '1558']


## Actividad 5 👩🏻‍💻

Dado el usuario ID:44, cree dos listas de películas recomendadas; la primera utilizando el algoritmo Most Popular y la segunda utilizando el algoritmo Slope One.

**Pregunta:** Realice un analisis apreciativo de las similitudes y diferencias entre ambas recomendaciones.

**Respuesta:**
ninguna similitud debido a que se basa en otras variables slope one (respecto a desviaciones y predicción) mientras que el popular solo recomienda todo lo que no hallas visto y sea popular

In [41]:
user_id = 300
top_n=8
for user_id in range(50,70,2):
  most_popular = pyreclab.MostPopular(dataset='u1.base',dlmchar=b'\t',header=False,usercol=0,itemcol=1,ratingcol=2)
  most_popular.train()
  ranking = [int(r) for r in most_popular.recommend(str(user_id), top_n, includeRated=False)]
  print('Rec con most popular {}: {}'.format(user_id, ranking))
  reclist_slopeone2 = mySlopeOne.recommend(str(user_id), top_n)
  print('Rec con slope One{}: {}'.format(user_id, reclist_slopeone2))

Rec con most popular 50: [50, 100, 258, 181, 294, 286, 288, 1]
Rec con slope One50: ['1472', '1556', '1599', '1201', '1498', '1492', '1027', '1500']
Rec con most popular 52: [50, 100, 258, 181, 286, 288, 1, 121]
Rec con slope One52: ['1064', '1651', '1650', '1645', '1636', '1585', '1604', '1547']
Rec con most popular 54: [50, 100, 258, 181, 294, 286, 288, 1]
Rec con slope One54: ['1653', '1599', '1512', '1450', '1536', '1467', '1201', '1500']
Rec con most popular 56: [50, 100, 258, 181, 286, 288, 1, 121]
Rec con slope One56: ['1536', '1463', '1293', '1512', '1599', '1064', '1500', '1656']
Rec con most popular 58: [50, 100, 258, 181, 286, 288, 1, 300]
Rec con slope One58: ['1653', '1599', '1536', '1500', '1064', '1450', '1463', '814']
Rec con most popular 60: [50, 100, 258, 181, 286, 288, 1, 300]
Rec con slope One60: ['1589', '1653', '1625', '1536', '1500', '1463', '1367', '814']
Rec con most popular 62: [258, 181, 286, 288, 127, 7, 98, 172]
Rec con slope One62: ['1536', '1450', '1463',